M48
; DRILL file {KiCad 6.0.8} date Sun 09 Oct 2022 04:42:20 PM PDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-09T16:42:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C7.200
%
G90
G05
T1
X100.0Y-59.65
T2
X100.0Y-84.65
T0
M30
